### ISSUE TITLE
Broken in Gnome 3.26.1 (antergos)

### ISSUE THREAD

**Issue by izznogooood** [laserb/gnome-shell-extension-suspend-button#28] opened 2017-10-17 17:00 UTC
No errors, but buttons dont do anything

Please let me know if I cant help.

**Comment by laserb** [comment] 2017-10-23 18:52
Are you sure it is version 3.2.1? That would be pretty old. Current version is 3.26.   
This could be related to #30

**Comment by izznogooood** [comment] 2017-10-23 20:02
No, its 3.26.1 ;)

**Comment by laserb** [comment] 2017-10-24 03:12
Ok, then it is a duplicate of #30.

**Closed by laserb** 2017-10-24 03:12 UTC
