### ISSUE TITLE
Buttons don't work on Gnome 3.26

### ISSUE THREAD

**Issue by ainola** [laserb/gnome-shell-extension-suspend-button#27] opened 2017-10-06 14:36 UTC
Ever since I updated to Gnome 3.26, neither the suspend button nor the power button work.

**Comment by Hasbreak** [comment] 2017-10-06 15:36
I can confirm that the bug also affects me on Arch.

**Comment by craigjackson** [comment] 2017-10-09 23:27
```
JS ERROR: TypeError: this.systemMenu._onSuspendClicked is not a function
                                          Extension<._onSuspendClicked@/home/xxxxxxxx/.local/share/gnome-shell/extensions/suspend-button@laserb/extension.js:192:9
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by jackpot51** [comment] 2017-10-09 23:34
Fixes here, if you are interested: https://github.com/system76/gnome-shell-extension-suspend-button

**Comment by asbachb** [comment] 2017-10-10 17:02
What's about a Pull Request? Or do you plan to publish it on gnome extensions?

**Comment by jackpot51** [comment] 2017-10-10 18:07
It was merged into this repository, so I would assume it would be available soon.

**Comment by laserb** [comment] 2017-10-10 18:17
The pull request is here: #24 . An updated version is under review and should be available soon.

**Comment by JanezStupar** [comment] 2017-10-16 18:55
@laserb 'sup?

**Comment by laserb** [comment] 2017-10-17 05:14
It is available now.

**Closed by laserb** 2017-10-17 05:14 UTC

**Comment by genodeftest** [comment] 2017-10-26 10:04
This extension update has been unpushed from extensions.gnome.org, right? I'm asking because I updated to the latest version and those buttons still don't work.

**Comment by laserb** [comment] 2017-10-26 11:26
Yes, it seemed to cause more problems than it solved. An updated version is on the way. But the reviewing process to get it on the extension site takes some time.

**Comment by laserb** [comment] 2017-10-27 04:15
New version is now available via extensions.gnome.org

**Comment by ainola** [comment] 2017-10-27 07:12
Thank you for your hard work, Sir.

**Comment by scr4bble** [comment] 2018-01-19 18:43
Hi,
this still doesn't work for me. Any ideas ?

`JS ERROR: TypeError: this.systemMenu._onSuspendClicked is not a function
                                            Extension<._onSuspendClicked@/home/xxxxx/.local/share/gnome-shell/extensions/suspend-button@laserb/extension.js:192:9
                                            wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22`

`$ gnome-shell --version
GNOME Shell 3.26.2
`
The extension is up to date.
